-- AlterTable
ALTER TABLE `deal` ADD COLUMN `costNote` VARCHAR(2000) NULL,
    ADD COLUMN `paidAmount` DECIMAL(18, 2) NULL,
    ADD COLUMN `quantity` DECIMAL(18, 2) NULL,
    ADD COLUMN `unitPrice` DECIMAL(18, 2) NULL,
    MODIFY `stage` ENUM('POTENTIAL', 'CONTACTED', 'NEGOTIATION', 'PENDING_CONTRACT_APPROVAL', 'CONTRACT', 'LOST') NOT NULL DEFAULT 'POTENTIAL';
